[package]
name = "rust-webassembly-hello-world"
version = "0.1.0"
authors = ["Christopher A. Taylor <mrcatid@gmail.com>"]

[dependencies]
stdweb = "0.4.12"           # A standard library for the client-side Web
